esphome:
  name: dht11
  platform: ESP8266
  board: esp01

wifi:
  ssid: !secret ssid
  password: !secret pass

logger:

api:

ota:

web_server:
  port: 80

sensor:
  - platform: dht
    model: DHT11
    pin: GPIO02
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 10s


