esphome:
  name: resensor
  platform: ESP8266
  board: d1_mini
  libraries:
    - ESP8266HTTPClient
    - ArduinoJson
  includes:
    - ../../../.platformio/packages/framework-arduinoespressif8266@2.20402.4/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h
    - ../../../.platformio/lib/ArduinoJson_ID64/src/ArduinoJson.h

wifi:
  ssid: !secret ap_ssid
  password: !secret ap_pass

logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: no

status_led:
  pin: 
    number: GPIO16
    inverted: yes

binary_sensor:
  - platform: template
    id: ws3
    name: "Water Sensor 3"
    device_class: moisture

interval:
  - interval: 10sec
    then:
      lambda: |-
          static HTTPClient http; 
          static String response;
          static int httpCode;
          static StaticJsonDocument<256> doc;
          static bool stateval;
          if (http.begin("http://" + WiFi.gatewayIP().toString() + "/switch/myled")) {
              httpCode = http.GET();
              if (httpCode == HTTP_CODE_OK) {
                response = http.getString();
                //
                deserializeJson(doc, response);
                JsonObject obj = doc.as<JsonObject>();
                stateval = obj["value"];
                doc.clear();
              }
              http.end();
          }
          //
          if (stateval != id(ws3).state) {
            id(ws3).publish_state(stateval);
          }

