esphome:
  name: espnowgw
  platform: ESP32
  board: esp32-poe
  includes:
  - espnow_common.h
  - espnowgw.h

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

logger:
  level: DEBUG

ota:
  port: 3232

web_server:
  port: 80

api:

globals:
- id: enid
  type: int[1]
  restore_value: yes

sensor:
- platform: custom
  lambda: |-
    auto ens = new EspNowSensor(1);
    App.register_component(ens);
    return ens->sensors;
  sensors:
  # Sensors
  - id: ens_tmp
    name: "ESP-NOW Data"

