esphome:
  name: esp32party
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret ssid
  password: !secret pass

logger:
  level: DEBUG

api:
  port: 6053

ota:
  port: 3232

web_server:
  port: 80

output:
  - platform: ledc
    pin: GPIO16
    id: pin16_output
light:
  - platform: monochromatic
    output: pin16_output
    id: spot0
    name: "Party Strip"
    effects:
      - strobe:
          name: Strobe
      - flicker:
          name: Flicker
          alpha: 50%
          intensity: 50%
      - lambda:
          name: Morse
          update_interval: 1s
          lambda: |-
            static int state = 0;
            auto call = id(spot0).turn_on();
            call.set_transition_length(1000);
            if (state == 0) {
              call.set_brightness(1.0);
            } else if (state == 1) {
              call.set_brightness(0.1);
            } else if (state == 2) {
              call.set_brightness(1.0);
            } else {
              call.set_brightness(0.1);
            }
            call.perform();
            state += 1;
            if (state > 5)
              state = 0;

