esphome:
  name: espcam01
  platform: ESP32
  board: esp-wrover-kit

wifi:
  networks:
  - ssid: !secret ssid 
    password: !secret pass
  reboot_timeout: 15min

logger:
  level: DEBUG

ota:
  port: 3232

web_server:
  port: 80

api:
  port: 6053

i2c:
  sda: 14
  scl: 15
  scan: True
esp32_camera:
  name: My Camera
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32


