esphome:
  name: hckk04
  platform: ESP8266
  board: d1_mini
  includes:
  - hckk04.h

logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

wifi:
  networks:
  - ssid: !secret ssid
    password: !secret pass
  power_save_mode: none
  fast_connect: no

api:

ota:
  port: 8266

#############################

status_led:
  pin:
    number: GPIO2
    inverted: True

sensor:
- platform: custom
  lambda: |-
    auto hckk04 = new HCKK04Sensor(112);
    App.register_component(hckk04);
    return { 
      hckk04->temperature_sensor,
      hckk04->humidity_sensor
    };
  sensors:
  - id: home_hckk04_tmp
    name: "Home HCKK04 Temperature"
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
    - debounce: 1s
  - id: home_hckk04_hum
    name: "Home HCKK04 Humidity"
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
    - debounce: 1s
