esphome:
  name: hckk04
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: True
  includes:
  - hckk04.h

logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

wifi:
  networks:
  - ssid: !secret ssid
    password: !secret pass
  power_save_mode: none
  fast_connect: no

api:
  services:
  - service: configure
    variables:
      code: int
    then:
    - lambda: "id(house_code) = code;"

ota:
  port: 8266

web_server:
  port: 80

#############################

status_led:
  pin:
    number: GPIO2
    inverted: True

globals:
- id: house_code
  type: int
  restore_value: yes
  initial_value: '0'

sensor:
- platform: custom
  lambda: |-
    auto hckk04 = new HCKK04Sensor();
    App.register_component(hckk04);
    return { 
      hckk04->temperature_sensor,
      hckk04->humidity_sensor
    };
  sensors:
  - id: home_hckk04_tmp
    name: "Home HCKK04 Temperature"
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
    - debounce: 1s
  - id: home_hckk04_hum
    name: "Home HCKK04 Humidity"
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
    - debounce: 1s

