esphome:
  name: xtree
  platform: ESP8266
  board: d1_mini

wifi:
#  networks:
#    ssid: !secret ssid
#    password: !secret pass
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_pass
#  use_address: 192.168.4.1
captive_portal:

logger:
ota:
web_server:

api:
  services:
  - service: click
    then:
    - script.stop: click1
    - script.execute: click1
  - service: clicks
    then:
    - script.stop: click8
    - script.execute: click8

switch:
- platform: gpio
  pin:
    number: 2
    inverted: yes
  id: io2
- platform: template
  id: x_mas_tree
  name: "X-mas Tree"
  icon: "mdi:pine-tree"
  turn_on_action:
  - switch.turn_on: io2
  - delay: 500ms
  - switch.turn_off: io2

binary_sensor:
- platform: gpio
  pin:
    number: 15
    inverted: yes
  name: "X-mas Button"

script:
- id: click1
  then:
    - switch.turn_on: x_mas_tree
- id: click8
  then:
    - switch.turn_on: x_mas_tree
    - delay: 1s
    - switch.turn_on: x_mas_tree
    - delay: 1s
    - switch.turn_on: x_mas_tree
    - delay: 1s
    - switch.turn_on: x_mas_tree
    - delay: 1s
    - switch.turn_on: x_mas_tree
    - delay: 1s
    - switch.turn_on: x_mas_tree
    - delay: 1s
    - switch.turn_on: x_mas_tree
    - delay: 1s
    - switch.turn_on: x_mas_tree

